* Update: Added manpages
open-switch/opx-alarm pull request #4
Opened 2018-06-18 22:33 UTC by hpersh

Change-Id: I584b03b28cf5f284912472a72febac26a020c916
Signed-off-by: Howard Persh <Howard_Persh@dell.com>

2018-06-19 13:41 UTC, amybuck requested changes
1. DESCRIPTION: This service monitors... (typo for monitors).
2. OPTIONS: If this option is not provided, the default configuration file is /etc/opx... (removed colon).
3. REPORTING BUGS: Replace "please refer" with "see https://...".
4. COPYRIGHT: (c) 2018 Dell Inc. or its subsidiaries. All Rights Reserved. (don't use the word copyright before the symbol).
5. Spell out all numbers under 10 in sentences. Example under Description: It has two purposes: Sentence should read: "This file configures the OPX alarm service, and serves two purposes:"
5. Bullets should start with an initial cap.
6. Replace leds with LEDs.
7. DellEMC is incorrect - proper is with a space in between as Dell EMC.
8. "The following are the contents..."

2018-06-20 19:02 UTC, hpersh commented
@amybuck 
1. Done.
2. Done.
3. Done.
4. Done.
5. Done.
6. Even if the bullet points are part of the same sentence?
7. leds (all lower case) is intentional; it is a literal all-lowercase keyword that occurs in the file.
8. Done.
9, Done.

2018-07-09 20:50 UTC, hpersh commented
Pull-request updated, HEAD is now 1be0176c30a4445fe1f574d7b696b18e2000f386

2018-07-09 20:52 UTC, jeffyin-dell approved these changes

2018-07-10 18:27 UTC, amybuck approved these changes

2018-07-10 18:30 UTC, merged